[feat] llgo/c/hyper-related c lib
goplus/llgo pull request #523
Opened 2024-07-16 03:51 UTC by spongehah

add new c libs:
`netdb`
`select`
`fddef`

2024-07-16 04:06 UTC, luoliwoshang requested changes

2024-07-16 04:06 UTC, luoliwoshang commented on c/netdb/netdb.go
> +func GetAddrInfo(host *c.Char, port *c.Char, addrInfo *AddrInfo, result **AddrInfo) c.Int
The style of these functions needs to be changed. `GetAddrInfo` should be changed to `Getaddrinfo` to maintain consistency with the auto-generation tool, which does not expect to process word breaks in the original symbol (e.g., getaddrinfo) into camel case naming.

2024-07-17 09:41 UTC, xushiwei commented
> add new c libs: `netdb` `select` `fddef`

- merge package `fddef`, `select` into `c/syscall`;
- keep `FD_ISSET`, `FD_SET`, etc. (that is, change `FdIsset ` => `FD_ISSET`, `Fdset ` => `FD_SET`, etc.

2024-07-17 09:44 UTC, xushiwei commented
> add new c libs: `netdb` `select` `fddef`

rename `c/socket` => `c/net` and merge package `netdb` into `c/net`.

2024-07-17 10:14 UTC, spongehah commented
> > add new c libs: `netdb` `select` `fddef`
> 
> * merge package `fddef`, `select` into `c/syscall` (put code in `c/syscall/select.go`);
> * keep `FD_ISSET`, `FD_SET`, etc. (that is, change `FdIsset ` => `FD_ISSET`, `Fdset ` => `FD_SET`, etc.

! [image] (https://github.com/user-attachments/assets/52b8d38c-8cf3-4072-a664-9a101b7a10cc)
Here LLGoPackage is conflicting

2024-07-17 16:03 UTC, xushiwei commented
> > > add new c libs: `netdb` `select` `fddef`
> > 
> > 
> > 
> > * merge package `fddef`, `select` into `c/syscall` (put code in `c/syscall/select.go`);
> > * keep `FD_ISSET`, `FD_SET`, etc. (that is, change `FdIsset ` => `FD_ISSET`, `Fdset ` => `FD_SET`, etc.
> 
> ! [image] (https://github.com/user-attachments/assets/52b8d38c-8cf3-4072-a664-9a101b7a10cc) Here LLGoPackage is conflicting

Merge package `select`, `fddef` to `c/sys`.

And

```go
const LLGoPackage = "link: c"
```

can be:

```go
const LLGoPackage = "link"
```

2024-07-18 08:33 UTC, xushiwei commented on c/sys/select.go
> +	"github.com/goplus/llgo/c/syscall"
put `llgo/c/xxx` packages together

2024-07-18 08:33 UTC, xushiwei commented on c/sys/select.go
> +type TimeVal struct {
put `TimeVal` to package `llgo/c/time`

2024-07-18 08:33 UTC, xushiwei commented on c/sys/select.go
> +	TvSec  c.Long
remove `Tv` prefix

2024-07-18 08:33 UTC, xushiwei commented on c/net/net.go
> +	AiFlags     c.Int
remove `Ai` prefix

2024-07-19 00:20 UTC, merged